- JessicaWhite/week_01/afternoon/calculator.js
- JessicaWhite/week_01/afternoon/drEvil.js
- JessicaWhite/week_01/afternoon/fixStart.js
- JessicaWhite/week_01/afternoon/index.html
- JessicaWhite/week_01/afternoon/main.js
- JessicaWhite/week_01/afternoon/main2.js
- JessicaWhite/week_01/afternoon/main3.js
- JessicaWhite/week_01/afternoon/mixUp.js
- JessicaWhite/week_01/afternoon/notBad.js
- JessicaWhite/week_01/afternoon/verbing.js
gibberish
1: how long
2: difficulty
3: what did you struggle with?
> actually adding homework

- AlexisFelicilda/week_01/4-28/index.html
- AlexisFelicilda/week_01/4-28/main.js
I would say for level of difficulty maybe an 8, at some point while doing it I kind of just sat there and thought how I am going to learn all of this... The hardest part for me is having the information but just deciding what and where I need to put it. I worked on it last night for about 3.5 hours; I tend over think allot of the problems.
> adding homework from last night

- MichaelBlack/week_01/160428/index.html
- MichaelBlack/week_01/160428/main.js
Difficulty: 3/10
Took some experimenting to figure out the string.slice() method
Total time ~ 2hours
> added week one homework

- DanielHarsanyi/week_01/28-1-16/calculator.js
- DanielHarsanyi/week_01/28-1-16/drEvil.js
- DanielHarsanyi/week_01/28-1-16/fixStart.js
- DanielHarsanyi/week_01/28-1-16/index.html
- DanielHarsanyi/week_01/28-1-16/mixUp.js
- DanielHarsanyi/week_01/28-1-16/notBad.js
- DanielHarsanyi/week_01/28-1-16/verbing.js
- Took a few hours
- 1.5/10 (was able to solve a couple of things with Google)
> Adding 28-1-16 HW

- MarkGo/week_01/index.html
- MarkGo/week_01/main.js
I found it very very hard and I worked on it for 3-4 hours.
> Thurs wk 1 Homework

- JessicaWhite/week_01/afternoon/calculator.js
- JessicaWhite/week_01/afternoon/drEvil.js
- JessicaWhite/week_01/afternoon/fixStart.js
- JessicaWhite/week_01/afternoon/index.html
- JessicaWhite/week_01/afternoon/main.js
- JessicaWhite/week_01/afternoon/main2.js
- JessicaWhite/week_01/afternoon/main3.js
- JessicaWhite/week_01/afternoon/mixUp.js
- JessicaWhite/week_01/afternoon/notBad.js
- JessicaWhite/week_01/afternoon/verbing.js
- YumiKo/week_01/HRloops/index.html
- YumiKo/week_01/HRloops/main.js
- YumiKo/week_01/arrays/index.html
- YumiKo/week_01/arrays/main.js
- YumiKo/week_01/mta/index.html
- YumiKo/week_01/mta/main.js
- YumiKo/week_01/objects/index.html
- YumiKo/week_01/objects/main.js
How long? MTA : 4hours / JS Bank : 1hour / Word Guesser : 1hour
Difficulty? average 
what did you struggle with?
- Tried to put user input in MTA but need more lessons
- debugger is very useful when dealing with function
> MTA/JS Bank/Word Guesser

- JessicaKang/week_01/loops_homework/index.html
- JessicaKang/week_01/loops_homework/main.js
How long? ~ 3 hours
Difficulty? 4/10
What did you struggle with? 
- Learning the string.slice
- Making multiple variables and putting them into a function seamlessly
- semi-colons!
> Week 1's Homework

- SigmundBautista/week_01/homework_thursday_27042016/index.html
- SigmundBautista/week_01/homework_thursday_27042016/main.js
Had alot of trouble on this one. 
struggled with for looping.
most likely will need with for looping and strings.
7 hours of failure.
> Homework for Thursday

- DonnZhao/week_01/MTA/index.html
- DonnZhao/week_01/MTA/main.js
- DonnZhao/week_01/exercises/index.html
- DonnZhao/week_01/exercises/main.js
- DonnZhao/week_01/exercises/main2.js
how long 
difficulty
which part
> home work last night

- NikMalev/week_01/leapyear.html
5/10 Difficulty
Struggled with mix up
Took approx. 1 hr
> Submitted leapyear homework

- JaneHogan/week_01/Janehomework1May/index.html
- JaneHogan/week_01/Janehomework1May/main.js
- JaneHogan/week_01/Janehomework28April/index.html
- JaneHogan/week_01/Janehomework28April/main.js
Oh boy.  This was hard, but I finally got it, because Simon helped me!
> woo hoo commit

- FabioCamatti/week_01/geometry-functions-lab/Imain.js
- FabioCamatti/week_01/geometry-functions-lab/index.html
- FabioCamatti/week_01/geometry-functions-lab/main.js
- FabioCamatti/week_01/js-homework-1/index.html
- FabioCamatti/week_01/js-homework-1/main.js
> fcamatti, homework files from 28 Apr 2016

- SigmundBautista/week_01/MTA/indexSig.html
- SigmundBautista/week_01/MTA/mainSig.js
Completed while under the influence of pain killers
took 5 hours.
was pretty hard
> MTA forgot to push

- MonaliSinghi/week_01/index.html
- MonaliSinghi/week_01/main.js
In these exercises we cover functions,Arrays,loop,object,logical operators. I find them little bit difficult.
> Week one homework.

- HarrisonChow/week_01/Exercises/ArrayAndFunctionExercises.js
- HarrisonChow/week_01/Exercises/index.html
- HarrisonChow/week_01/MTA/MTA.js
- HarrisonChow/week_01/MTA/index.html
- HarrisonChow/week_01/TheWordGuesser/hangman.html
- HarrisonChow/week_01/TheWordGuesser/hangman.js
- HarrisonChow/week_01/TheWordGuesser/index.html
- HarrisonChow/week_01/TheWordGuesser/theWordGuesser.js
- HarrisonChow/week_01/TheWordGuesser/wheelOfFortune.html
- HarrisonChow/week_01/TheWordGuesser/wheelOfFortune.js
- HarrisonChow/week_01/geometryFunctionLab/geometryFunctionLab.js
- HarrisonChow/week_01/geometryFunctionLab/index.html
- HarrisonChow/week_01/javaScriptBank/index.html
- HarrisonChow/week_01/javaScriptBank/javaScriptBank.js
> Home work week one 20160501

- SigmundBautista/week_02/ famous_computer_scientist_fansite/bio.html
- SigmundBautista/week_02/ famous_computer_scientist_fansite/index.html
- SigmundBautista/week_02/ famous_computer_scientist_fansite/other.html
- SigmundBautista/week_02/ famous_computer_scientist_fansite/styles.css
Completed task
Pretty easy
completed in 2 hours
was absent due to illness
> homework Famous fansite

- JessicaWhite/week_02/lolcats/index.html
- JessicaWhite/week_02/lolcats/main.js
- JessicaWhite/week_02/lolcats/style.css
- JessicaWhite/week_04/ruby_calculator/calculator.rb
Things I like: Ruby makes sense.
Things I don't like: Ruby makes too much sense and I don't trust it and it's going to be really hard to switch back to JavaScript after this.
> Adding Ruby Calculator

- DonnZhao/week_04/Calculator.rb
- DonnZhao/week_04/Calculator_homework/Calculator.rb
- DonnZhao/week_04/Calculator_homework/multi_calculator.rb
update ruby homework && tictactoe, any commit appreciate.
> upload ruby homework monday

- HarrisonChow/week_04/calc.rb
> homework 20160516

- AlexisFelicilda/week_04/calculator/bmi.rb
- AlexisFelicilda/week_04/calculator/calc.rb
- AlexisFelicilda/week_04/calculator/mortgage.rb
- AlexisFelicilda/week_04/calculator/trip.rb
Ruby for some reason is easier for me to understand than JS. I think the only thing that might confuse me is when to use if,elsif, else.... and I guess just writing it properly; problem solving but hey it's only 1 day right...
> homework week 4 day 1

- JessicaKang/week_04/bmi.rb
- JessicaKang/week_04/calc.rb
- JessicaKang/week_04/trip_calculator.rb
> May 16th Homework

- HarrisonChow/week_04/mta.rb
> mta in ruby

- HarrisonChow/week_04/movie_search/main.rb
- HarrisonChow/week_04/movie_search/views/error.erb
- HarrisonChow/week_04/movie_search/views/home.erb
- HarrisonChow/week_04/movie_search/views/layout.erb
- HarrisonChow/week_04/movie_search/views/list.erb
- HarrisonChow/week_04/movie_search/views/result.erb
- HarrisonChow/week_04/movie_search/views/search.erb
- HarrisonChow/week_04/mta.rb
homework 20160518
week 04 day 3
> movie search
